### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by cristiandouce** [modella/mongo#3]
Please, tell me if I'm wrong... but, is it possible that this plugin would open a mongo connection per each model usage?

Thanks!

**Comment by rschmukler** [comment]
Nice point. This is something that I will have to clarify in the `README.md`. Please let me know if this makes sense @cristiandouce.

## A Note about connection usage

Each call to `modella-mongo` will open up a mongo connection, and return a function that can be used as a plugin for ANY Modella model. 

As such it is recommended that you export the result of `modella-mongo` and then use that for all of your models.

### Example of BAD way

`models/user.js`

``` js
...
var mongo = require('modella-mongo')('localhost/my-db');
User.use(mongo);
...
```

`models/post.js`

``` js
...
var mongo = require('modella-mongo')('localhost/my-db');
Post.use(mongo);
...
```

In the above example both the `User` and `Post` model will open a connection to the mongo database.

### Example of better way

`config/modella-db.js`

``` js
var mongo = module.exports = require('modella-mongo')('localhost/my-db');
```

`models/user.js`

``` js
...
var configuredDb = require('../config/modella-db');
User.use(configuredDb);
...
```

`models/post.js`

``` js
...
var configuredDb = require('../config/modella-db');
Post.use(configuredDb);
...
```

Here `modella-db.js` configures the mongo database,  and then both models use it.

**Comment by cristiandouce** [comment]
haha, yeah! Thanks!

I came with the same solution right after I submitted the issue.
Only I named it `lib/mongo-plugin`... 
`modella-db` sounds more appropiate though.

I'm working on a "bootstrap" app demo like the one I did with @gravityonmars [nodejs-starter](https://github.com/gravityonmars/nodejs-starter) but with `modella` instead. Just to try it out.

Thanks for the clarifying example!

**Comment by rschmukler** [comment]
@cristiandouce Sounds awesome! I like the stack. I'd recommend swapping out [rework](http://github.com/visionmedia/rework) / [styl](http://github.com/visionmedia/styl) for `stylus` (stylus can become damn slow on large projects). Also, since I see you're using `component-stylus-plugin`, I also wrote [component-styl-plugin](http://github.com/rschmukler/component-styl-plugin). 

I haven't updated the documentation though, but if you read the source you should be able to figure out the options. Maybe tomorrow or this weekend...

**Comment by cristiandouce** [comment]
Awesome. Thanks! I'll take a look to those too. :facepunch:
